name: test

on: [push]

env:
  CARGO_TERM_COLOR: always


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
      - name: Install test dependencies
        run: python -m pip install -r test-requirements.txt
      - name: End-to-end tests
        run: python -m pytest integration_tests

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
      - name: Install test dependencies
        run: python -m pip install -r test-requirements.txt
      - name: Linting
        run: python -m flake8 integration_tests
      - name: Code style checks
        run: find integration_tests -name '*.py' -and -not -name 'ninja_syntax.py' | xargs python -m yapf --diff
